### ISSUE TITLE
Error running tf_record_writer

### ISSUE THREAD

**Issue by EvanZ** [artem-oppermann/Deep-Autoencoders-For-Collaborative-Filtering#1]
Getting the following errors:

```
Traceback (most recent call last):
  File "data/tf_record_writer.py", line 81, in <module>
    main()
  File "data/tf_record_writer.py", line 57, in main
    with tf.python_io.TFRecordWriter(tf_filename) as tfrecord_writer:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: TRAIN/train_001.tfrecord; No such file or directory
```

**Comment by EvanZ** [comment]
Sorry figured it out. Needed to create those TRAIN/TEST directories first!
