### ISSUE TITLE
error when running training.py

### ISSUE THREAD

**Issue by BaomingLee** [artem-oppermann/Deep-Autoencoders-For-Collaborative-Filtering#8]
Hello, I run the training.py, but get this error:

WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /Users/ming/Desktop/Msc Project/Code/Deep-Autoencoders-For-Collaborative-Filtering/src/model/train_model.py:26: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
return fn(*args)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
[[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "training.py", line 114, in 
tf.app.run()
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "training.py", line 92, in main
, loss=sess.run((train_op, train_loss_op))
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
run_metadata_ptr)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
feed_dict_tensor, options, run_metadata)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
run_metadata)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
[[node IteratorGetNext (defined at training.py:66) ]]

Caused by op 'IteratorGetNext', defined at:
File "training.py", line 114, in 
tf.app.run()
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "training.py", line 66, in main
x_train= iter_train.get_next()
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 414, in get_next
output_shapes=self._structure._flat_shapes, name=name)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1685, in iterator_get_next
output_shapes=output_shapes, name=name)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
op_def=op_def)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
return func(*args, **kwargs)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
op_def=op_def)
File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in init
self._traceback = tf_stack.extract_stack()

DataLossError (see above for traceback): corrupted record at 0
[[node IteratorGetNext (defined at training.py:66) ]]

**Comment by BaomingLee** [comment]
> Hello, I run the training.py, but get this error:
> 
> WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From /Users/ming/Desktop/Msc Project/Code/Deep-Autoencoders-For-Collaborative-Filtering/src/model/train_model.py:26: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.
> Traceback (most recent call last):
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
> return fn(*args)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
> [[{{node IteratorGetNext}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "training.py", line 114, in
> tf.app.run()
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "training.py", line 92, in main
> , loss=sess.run((train_op, train_loss_op))
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
> run_metadata_ptr)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
> feed_dict_tensor, options, run_metadata)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
> run_metadata)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
> [[node IteratorGetNext (defined at training.py:66) ]]
> 
> Caused by op 'IteratorGetNext', defined at:
> File "training.py", line 114, in
> tf.app.run()
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "training.py", line 66, in main
> x_train= iter_train.get_next()
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 414, in get_next
> output_shapes=self._structure._flat_shapes, name=name)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1685, in iterator_get_next
> output_shapes=output_shapes, name=name)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
> op_def=op_def)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
> return func(*args, **kwargs)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
> op_def=op_def)
> File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in init
> self._traceback = tf_stack.extract_stack()
> 
> DataLossError (see above for traceback): corrupted record at 0
> [[node IteratorGetNext (defined at training.py:66) ]]

I solve it already~
